.TH BLITZ-SDL 6 "Version 1.1" "Craig McPartland"

.SH NAME
blitz-sdl \- game in which you must bomb buildings to land plane

.SH SYNOPSIS
.TP 6
\fBblitz-sdl\fP

.SH DESCRIPTION
\fBblitz-sdl\fP is a simple game.

This game is based on the VIC-20 game, Blitz.  The aim is to destroy
all of the buildings by dropping bombs from your plane.  After all 
of the buildings have been destroyed, the next level begins with
taller buildings.  Don't worry - nobody lives in the buildings.

.SH COMMANDS
P - pauses the game
.br
Esc - quits the game
.br
S - mutes / unmutes the sound
.br
Any other key - drops a bomb

.SH AUTHORS
Craig McPartland <craig.jmcp@gmail.com>

.SH BUGS
I expect so.
